language: android
jdk: oraclejdk8
before_install:
  - export JAVA8_HOME=$JAVA_HOME
android:
  components:
  - build-tools-23.0.0_rc2
  - android-22
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-support
  - extra-android-m2repository
  - addon-google_apis-google-22

script:
  - ./gradlew test -PdisablePreDex
notifications:
  hipchat:
    rooms:
      secure: KFRLdAAmWJ1tW0VxMAuh3NPJwSx5RnuTsvtd3hrmknYhAyKQ1mzi9leOLelXJ0Iix9DXsaC1/a7Syc7Q3pw79IyXOpIdY77Ls/uQY/y23XlnsTFYlmoEjzL7GDiZzTuPsG9ddpuBdzmVs3DknA2KCG5ZZBaG2IEJ/MHDu5IiNpo=
