language: android
android:
  components:
  - build-tools-19.1.0
  - android-19
script: ./gradlew build
notifications:
  hipchat:
    rooms:
      secure: KFRLdAAmWJ1tW0VxMAuh3NPJwSx5RnuTsvtd3hrmknYhAyKQ1mzi9leOLelXJ0Iix9DXsaC1/a7Syc7Q3pw79IyXOpIdY77Ls/uQY/y23XlnsTFYlmoEjzL7GDiZzTuPsG9ddpuBdzmVs3DknA2KCG5ZZBaG2IEJ/MHDu5IiNpo=
